### ISSUE TITLE
Python 3 compatibility suggestion

### ISSUE THREAD

**Issue by cp2004** [barrettford/Octoprint-Usb_keyboard#1]
Hey, just saw the notification for listing on the plugin repo. Thought I'd suggest a quick change to make your life a little easier, WRT people not reading the compatibility info for Python 3.

This line:
https://github.com/barrettford/Octoprint-Usb_keyboard/blob/3bda2ebbfb5b79deb458e4a6e34420d5aadbcc4a/setup.py#L68

Is more useful if you change it to:
```diff
- additional_setup_parameters = {}
+ additional_setup_parameters = {"python_requires": ">=3,<4"}
```

People don't always read when you specify Python versions, and you will get people try and install it anyway. With this line, pip prints something like this:
```
ERROR: Package 'octoprint_usb_keyboard' requires a different Python: 2.7.17 not in '>=3, <4'
```

It might help. Have the link to the Py3 upgrade script or OctoPi 0.18 handy for the inevitable issues. While Py3 is still minority (14%) it is growing, plugins like this accelerate this transition. 🙂

**Comment by barrettford** [comment]
Thanks for the tip!  That's a great idea

**Comment by barrettford** [comment]
Fixed in https://github.com/barrettford/Octoprint-Usb_keyboard/commit/5b784c565af086d84f999595d164c7d2e7132f57

**Comment by barrettford** [comment]
I bought [this 10key](https://smile.amazon.com/gp/product/B07FFLNF5C).  It's a mechanical one with replaceable keycaps that I've started printing replacements for.  It's works really well.  BTW, the 10key examples in the plugin are designed around this keypad.

**Comment by cp2004** [comment]
Thanks for the suggestion!
