### ISSUE TITLE
Allow commands while paused but not while printing?

### ISSUE THREAD

**Issue by grantemsley** [barrettford/Octoprint-Usb_keyboard#10]
Thanks for the awesome plugin!  Been wanting something like this for awhile.

I'd love if there was the option to have commands you can send while not printing and while paused, but not while actually printing.  It looks like the code treats PRINTING and PAUSED both as printing for that purpose.

Use case:  I want two buttons, one that raises the Z axis a few cm, and another that lowers it back. I use this when clearing nozzle clogs or buildup to get the nozzle up out of the way of the partially finished print and get pliers in there.

Octoprint itself allows you to use the movement controls while paused, but not while printing. That's the behaviour I'd like from the buttons.

**Comment by barrettford** [comment]
Well, I'm afraid of doing that since not everyone's pause continues in the same way.  For some people, resume simply continues on from right where you are, which could result in people's prints failing in midair...

**Comment by barrettford** [comment]
I suppose I can make that change for now and worry about it later if people complain.

**Comment by barrettford** [comment]
Fixed in https://github.com/barrettford/Octoprint-Usb_keyboard/commit/74bfaa3deba7dbb6edd822d74fe508762011c9e4
Please give it a try and tell me if it works.

**Comment by barrettford** [comment]
bug fixed, new release https://github.com/barrettford/Octoprint-Usb_keyboard/releases/tag/v0.2.1
