### ISSUE TITLE
Moving of commands moves the wrong one

### ISSUE THREAD

**Issue by Rednax74** [barrettford/Octoprint-Usb_keyboard#11]
Great plugin by the way, helps a lot to get stuff done directly at the printer without the need to go through all the lcd menues!
I noticed an issue with the move command arrows: if you have several identical command blocks and you want to move the third one always the top identical one was moved instead. As a workaround I could add spaces so that I could move each block seperately. So in the attached picture I had a typo in the G0 Z0.3 part and added it anew and instead of moving the new lowest command alsways the top one was moved. 
While we are at it: it would be great if the commandlines could be edited directly: either I missed something but I could not edit an existing line so I added the corrected one and deleted the old one but that seems to be somewhat complicated.
Cheers
Alex
![image](https://user-images.githubusercontent.com/78152641/106141435-5d087980-6170-11eb-9894-da0adc0fd76c.png)

**Comment by barrettford** [comment]
Ah, totally a bug! I see what I did there...  Working on a fix for this and https://github.com/barrettford/Octoprint-Usb_keyboard/issues/10 right now.

**Comment by barrettford** [comment]
Fixed in https://github.com/barrettford/Octoprint-Usb_keyboard/commit/74bfaa3deba7dbb6edd822d74fe508762011c9e4
Please give it a try and tell me if it works.

Install newest version manually with https://github.com/barrettford/OctoPrint-Usb_keyboard/archive/master.zip if you want to test before the notification comes in.

**Comment by barrettford** [comment]
bug fixed, new release https://github.com/barrettford/Octoprint-Usb_keyboard/releases/tag/v0.2.1

**Comment by Rednax74** [comment]
Alright, bug is fixed and in place editing works, great stuff, thanks for the fast response!
