### ISSUE TITLE
Warn about breaking update

### ISSUE THREAD

**Issue by decay42** [barrettford/Octoprint-Usb_keyboard#13]
> Redesigned how Gcode is stored in config and handled in the settings dialog. This required updating the schema.

You should state more clearly that this will break your current configuration .. kinda frustrating that there is no backwards compatibility.

**Comment by barrettford** [comment]
Well, it wasn't supposed to break... I've tested it on my own pi and it didn't... Do you have a discord?  I can walk you through restoring your config.

**Comment by decay42** [comment]
Yes I do, that would be very helpful, thank you. Though I dont really want to publish it here on Github. Do you have a server I can join?

**Comment by barrettford** [comment]
Discord me at LonelyTeacup#0950

**Comment by barrettford** [comment]
Glad we got your settings restored.  Sorry about that!
New release with fix https://github.com/barrettford/Octoprint-Usb_keyboard/releases/tag/v0.2.1
