### ISSUE TITLE
Problems with Variables

### ISSUE THREAD

**Issue by Sound-Techniker** [barrettford/Octoprint-Usb_keyboard#17]
Hello 
I've been biting my teeth today to make the variables changeable.
After I have changed the Json file manually and assigned the key values by myself it now also works. About the interface I have not managed it.
In between, I also noticed that the back import of an exported profile destroys the labels.

thank you for your effort I like the plugin well

**Comment by barrettford** [comment]
You need to explain things better than that.

Do you have any pictures?  Can you walk me through what you tried?  If you want to talk through Discord, can you pose your Discord ID?

**Comment by Sound-Techniker** [comment]
hello of course,

First problem:

1. plugin installed. logical ;-)
2. profile 10Key with Example 10key - pynput with symbols activated. To see first how the whole thing works.
Works fine.
3. copied the profile. 
4. exported the copied profile.
5. import the copied profile again. Ends in the following:

![screen_20210210_121953](https://user-images.githubusercontent.com/48445427/107505590-3a795600-6b9d-11eb-991c-7be04196b470.png)



Second problem:
I cannot delete incorrectly added release commands by clicking on "minus".

![screen_20210210_124205](https://user-images.githubusercontent.com/48445427/107505720-685e9a80-6b9d-11eb-8ab9-dcc96573c761.png)


Third problem:
Completely empty profile created. Created the keys maped and added commands.
I followed the 10Key example profile. Almost everything worked as far as it could. Until I was checking the functions and got stuck when changing the variables. Holding down the "," key and pressing "3" to save 100 in the variable "distance" had no effect. I then realized (after looking in the json file) that I had not assigned any alternate variable values to the 0,1,2,3 keys.
I clicked on the variable info and got the explanation. but I couldn't create any values (see picture). 

![screen_20210210_124239](https://user-images.githubusercontent.com/48445427/107505860-97750c00-6b9d-11eb-9f3e-1dca8fa34f8e.png)


when that didn't work, I simply created an object in the json file under variables of the corresponding key with the values and variables. after importing the customized jason file, it worked. 

![screen_20210210_124451](https://user-images.githubusercontent.com/48445427/107506039-d014e580-6b9d-11eb-8a5d-8de1f4327c03.png)

fourth problem that I just ran across the way

when inserting a custom commando with gcode i can't customize the options

![screen_20210210_125109](https://user-images.githubusercontent.com/48445427/107506680-b9bb5980-6b9e-11eb-88d0-d0b809785cd1.png)



I suspect that simply the user interface is the problem.
I had also deactivated all other plugins to exclude that the error does not come from somewhere else

Hope now its little more helpfull.
Thankyou for your fast response

**Comment by barrettford** [comment]
I have confirmed the Unicode character import bug, I'm working on it.  Thanks for the report!

I'm still investigating the other bugs.

**Comment by barrettford** [comment]
I've confirmed the variables UI bug, and the released commands field bug.

**Comment by barrettford** [comment]
K, I have a branch with fixes on it, if you'd be willing to give it a try:
Use the Octoprint Plugin Manager and manually install:
https://github.com/barrettford/OctoPrint-Usb_keyboard/archive/fix-import.zip

**Comment by Sound-Techniker** [comment]
hi, i lokked into the fix.

I tested the first second third and fourth Problem. 
Only two things i have found. The Variable and the Value ist not stored. So that i have to do also the Json file edit.
after this editet Json file Import i got a little key name bug between home xy and home z.

Import key name bug:
![screen_20210210_192839](https://user-images.githubusercontent.com/48445427/107555450-7af5c580-6bd7-11eb-9c3b-c0ce1368455c.png)

Store variable value issue:
![screen_20210210_192906](https://user-images.githubusercontent.com/48445427/107555430-74674e00-6bd7-11eb-9a1d-1d501a247f2d.png)

Thank you so much for the fast support.
I like this Plug-in

**Comment by Sound-Techniker** [comment]
oh i just see i accidentally mixed up the picture headings. =-)

**Comment by barrettford** [comment]
send_while_printing is no longer a supported field, and the migration should have removed it.  What is your current plugin version?

**Comment by barrettford** [comment]
I my testing, variables are saving just fine.  Unicode is also being saved, exported, and imported without issue.  Do you want to screen-share with me and we can figure it out?

**Comment by Sound-Techniker** [comment]
Hello 
i testet again to store the Variable on a key. last time i forgot simply too press the "+" behind. Sorry that was my fault.
Thank you so much for your support :-) 🥇
