### ISSUE TITLE
Multiple Variables in Gcode Commands

### ISSUE THREAD

**Issue by Sound-Techniker** [barrettford/Octoprint-Usb_keyboard#19]
Hi 
I´m again ;-)

I would move to Spezial Positions on X and Y axis.
So i made two Variables and add these in Gcode Command.
When i wish to move to other positions i can change easy the Variables.
Like `G0 X<xdifLeft> Y<ydifFront> F6000`.

![screen_20210221_161237](https://user-images.githubusercontent.com/48445427/108629874-45b46780-7462-11eb-813c-0f644274d50b.png)

But after Storing on Key pressed nothing happens.
After this not Work i try to put only one Variable in a Gcode Command.
Like ´G0 X<xdifLeft>`
and ´G0 Y<ydifFront>`
But this results in move first X axis and after this Y axis.

![screen_20210221_161221](https://user-images.githubusercontent.com/48445427/108629879-4947ee80-7462-11eb-864e-588f6e45ccc4.png)

I  use Version (0.2.3).

And little bug again with the buttons for Gcode Commands send while Print and Pause buttons.

**Comment by barrettford** [comment]
I'll take a look.

**Comment by barrettford** [comment]
K, try installing this version and tell me if it fixes the variable problem.

https://github.com/barrettford/OctoPrint-Usb_keyboard/archive/investigate-substitution.zip

**Comment by Sound-Techniker** [comment]
Hi, 

Great!
i testet your new Code and i can now use 2 Variables in gcode commands.
i´m not testet more or less variables in commands. would it also work?

here my profile before testet the multiple Variables.

`{"key":"RP","value":{"commands":[{"alias":"Listening","key":"kpdot","value":{"pressed":[{"type":"listen_vars","variables":["distance","bed","hotend"]}],"released":[{"command":"confirm_last_command","presses_required":1,"type":"octoprint"},{"type":"save_vars","variables":["distance","bed","hotend"]}],"variables":[]}},{"alias":"HR","key":"kp9","value":{"pressed":[{"gcode":[{"code":"G0 X160 Y220 F6000","id":59525}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"Y-","key":"kp8","value":{"pressed":[{"gcode":[{"code":"G91","id":35974},{"code":"G0 Y+<distance> F6000","id":20560},{"code":"G90","id":51196}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"HL","key":"kp7","value":{"pressed":[{"gcode":[{"code":"G0 X60 Y 220 F6000","id":4832}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"X+","key":"kp6","value":{"pressed":[{"gcode":[{"code":"G91","id":63816},{"code":"G0 X+<distance> F6000","id":64432},{"code":"G90","id":52764}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{"key":"hotend","value":"210"}]}},{"alias":"Mitte","key":"kp5","value":{"pressed":[{"gcode":[{"code":"G0 X110 Y140 F6000","id":58834}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{"key":"hotend","value":"90"}]}},{"alias":"X-","key":"kp4","value":{"pressed":[{"gcode":[{"code":"G91","id":15914},{"code":"G0 X-<distance> F6000","id":6566},{"code":"G90","id":23145}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{"key":"hotend","value":"0"}]}},{"alias":"VR","key":"kp3","value":{"pressed":[{"gcode":[{"code":"G0 X160 Y60 F6000","id":55531}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{"key":"distance","value":100}]}},{"alias":"Y+","key":"kp2","value":{"pressed":[{"gcode":[{"code":"G91","id":20644},{"code":"G1 Y-<distance> F6000","id":41683},{"code":"G90","id":22274}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{"key":"distance","value":10}]}},{"alias":"VL","key":"kp1","value":{"pressed":[{"gcode":[{"code":"G0 X60 Y60> F6000","id":13871}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{"key":"distance","value":1}]}},{"alias":"E-","key":"kbminus","value":{"pressed":[{"gcode":[{"code":"G91","id":55988},{"code":"G1 E-<distance> F300","id":24201},{"code":"G90","id":55691}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"E+","key":"kpminus","value":{"pressed":[{"gcode":[{"code":"G91","id":62326},{"code":"G1 E+<distance> F300","id":19006},{"code":"G90","id":5280}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"Heizen","key":"kpslash","value":{"pressed":[{"gcode":[{"code":"M104 S<hotend>","id":56234}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"Z-","key":"backspace","value":{"pressed":[{"gcode":[{"code":"G91","id":61467},{"code":"G1 Z-<distance> F300","id":50132},{"code":"G90","id":45298}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":" Z+","key":"kpplus","value":{"pressed":[{"gcode":[{"code":"G91","id":13172},{"code":"G1 Z+<distance> F300","id":59872},{"code":"G90","id":6483}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"Home Z","key":"kpenter","value":{"pressed":[{"gcode":[{"code":"G28 Z","id":38409}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[]}},{"alias":"home XY","key":"kp0","value":{"pressed":[{"gcode":[{"code":"G28 X Y","id":57126}],"send_while_printing":false,"type":"printer"}],"released":[],"variables":[{" value":0.1,"key":"distance"}]}},{"alias":"PSU","key":"numlock","value":{"pressed":[{"command":"toggle","hotend_max":50,"type":"plugin_psucontrol"}],"released":[],"variables":[]}}],"description":"","keyboard":{"board":[{"keys":[]},{"keys":[{"alias":"PSU","h":1,"key":"numlock","w":1},{"alias":"Heizen","h":1,"key":"kpslash","w":1},{"alias":"E-","h":1,"key":"kbminus","w":1},{"alias":"E+","h":1,"key":"kpminus","w":1}]},{"keys":[{"alias":"HL","h":1,"key":"kp7","w":1},{"alias":"Y-","h":1,"key":"kp8","w":1},{"alias":"HR","h":1,"key":"kp9","w":1},{"alias":"Z+","h":1,"key":"kpplus","w":1}]},{"keys":[{"alias":"X-","h":1,"key":"kp4","w":1},{"alias":"Mitte","h":1,"key":"kp5","w":1},{"alias":"X+","h":1,"key":"kp6","w":1},{"alias":"Z-","h":1,"key":"backspace","w":1}]},{"keys":[{"alias":"VL","h":1,"key":"kp1","w":1},{"alias":"Y+","h":1,"key":"kp2","w":1},{"alias":"VR","h":1,"key":"kp3","w":1},{"alias":"Home Z","h":2,"key":"kpenter","w":1}]},{"keys":[{"alias":"Home XY","h":1,"key":"0","w":2},{"alias":"Settings","h":1,"key":"kpdot","w":1}]}],"scale":4},"variables":[{"key":"distance","value":"1"},{"key":"bed","value":60},{"key":"hotend","value":210},{"key":"xdifLeft","value":"60"},{"key":"xdifRight","value":"160"},{"key":"ydifFront","value":"60"},{"key":"ydifBack","value":"220"},{"key":"yf","value":"60"},{"key":"xl","value":"60"}]}}`

**Comment by barrettford** [comment]
It should now handle any number of variables.

I've modified your profile.  Import the following profile and tell me if it fixes the "send while printing" stuff.

`{"key":"RP","value":{"commands":[{"alias":"Listening","key":"kpdot","value":{"pressed":[{"type":"listen_vars","variables":["distance","bed","hotend"]}],"released":[{"command":"confirm_last_command","presses_required":1,"type":"octoprint"},{"type":"save_vars","variables":["distance","bed","hotend"]}],"variables":[]}},{"alias":"HR","key":"kp9","value":{"pressed":[{"gcode":[{"code":"G0 X160 Y220 F6000","id":59525}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"Y-","key":"kp8","value":{"pressed":[{"gcode":[{"code":"G91","id":35974},{"code":"G0 Y+<distance> F6000","id":20560},{"code":"G90","id":51196}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"HL","key":"kp7","value":{"pressed":[{"gcode":[{"code":"G0 X60 Y 220 F6000","id":4832}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"X+","key":"kp6","value":{"pressed":[{"gcode":[{"code":"G91","id":63816},{"code":"G0 X+<distance> F6000","id":64432},{"code":"G90","id":52764}],"options":"","type":"printer"}],"released":[],"variables":[{"key":"hotend","value":"210"}]}},{"alias":"Mitte","key":"kp5","value":{"pressed":[{"gcode":[{"code":"G0 X110 Y140 F6000","id":58834}],"options":"","type":"printer"}],"released":[],"variables":[{"key":"hotend","value":"90"}]}},{"alias":"X-","key":"kp4","value":{"pressed":[{"gcode":[{"code":"G91","id":15914},{"code":"G0 X-<distance> F6000","id":6566},{"code":"G90","id":23145}],"options":"","type":"printer"}],"released":[],"variables":[{"key":"hotend","value":"0"}]}},{"alias":"VR","key":"kp3","value":{"pressed":[{"gcode":[{"code":"G0 X160 Y60 F6000","id":55531}],"options":"","type":"printer"}],"released":[],"variables":[{"key":"distance","value":100}]}},{"alias":"Y+","key":"kp2","value":{"pressed":[{"gcode":[{"code":"G91","id":20644},{"code":"G1 Y-<distance> F6000","id":41683},{"code":"G90","id":22274}],"options":"","type":"printer"}],"released":[],"variables":[{"key":"distance","value":10}]}},{"alias":"VL","key":"kp1","value":{"pressed":[{"gcode":[{"code":"G0 X60 Y60> F6000","id":13871}],"options":"","type":"printer"}],"released":[],"variables":[{"key":"distance","value":1}]}},{"alias":"E-","key":"kbminus","value":{"pressed":[{"gcode":[{"code":"G91","id":55988},{"code":"G1 E-<distance> F300","id":24201},{"code":"G90","id":55691}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"E+","key":"kpminus","value":{"pressed":[{"gcode":[{"code":"G91","id":62326},{"code":"G1 E+<distance> F300","id":19006},{"code":"G90","id":5280}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"Heizen","key":"kpslash","value":{"pressed":[{"gcode":[{"code":"M104 S<hotend>","id":56234}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"Z-","key":"backspace","value":{"pressed":[{"gcode":[{"code":"G91","id":61467},{"code":"G1 Z-<distance> F300","id":50132},{"code":"G90","id":45298}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":" Z+","key":"kpplus","value":{"pressed":[{"gcode":[{"code":"G91","id":13172},{"code":"G1 Z+<distance> F300","id":59872},{"code":"G90","id":6483}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"Home Z","key":"kpenter","value":{"pressed":[{"gcode":[{"code":"G28 Z","id":38409}],"options":"","type":"printer"}],"released":[],"variables":[]}},{"alias":"home XY","key":"kp0","value":{"pressed":[{"gcode":[{"code":"G28 X Y","id":57126}],"options":"","type":"printer"}],"released":[],"variables":[{" value":0.1,"key":"distance"}]}},{"alias":"PSU","key":"numlock","value":{"pressed":[{"command":"toggle","hotend_max":50,"type":"plugin_psucontrol"}],"released":[],"variables":[]}}],"description":"","keyboard":{"board":[{"keys":[]},{"keys":[{"alias":"PSU","h":1,"key":"numlock","w":1},{"alias":"Heizen","h":1,"key":"kpslash","w":1},{"alias":"E-","h":1,"key":"kbminus","w":1},{"alias":"E+","h":1,"key":"kpminus","w":1}]},{"keys":[{"alias":"HL","h":1,"key":"kp7","w":1},{"alias":"Y-","h":1,"key":"kp8","w":1},{"alias":"HR","h":1,"key":"kp9","w":1},{"alias":"Z+","h":1,"key":"kpplus","w":1}]},{"keys":[{"alias":"X-","h":1,"key":"kp4","w":1},{"alias":"Mitte","h":1,"key":"kp5","w":1},{"alias":"X+","h":1,"key":"kp6","w":1},{"alias":"Z-","h":1,"key":"backspace","w":1}]},{"keys":[{"alias":"VL","h":1,"key":"kp1","w":1},{"alias":"Y+","h":1,"key":"kp2","w":1},{"alias":"VR","h":1,"key":"kp3","w":1},{"alias":"Home Z","h":2,"key":"kpenter","w":1}]},{"keys":[{"alias":"Home XY","h":1,"key":"0","w":2},{"alias":"Settings","h":1,"key":"kpdot","w":1}]}],"scale":4},"variables":[{"key":"distance","value":"1"},{"key":"bed","value":60},{"key":"hotend","value":210},{"key":"xdifLeft","value":"60"},{"key":"xdifRight","value":"160"},{"key":"ydifFront","value":"60"},{"key":"ydifBack","value":"220"},{"key":"yf","value":"60"},{"key":"xl","value":"60"}]}}`

**Comment by Sound-Techniker** [comment]
Hi,
i have testet positiv your fixed json. Thank you so much.
What was the Problem? May be export and reimport?

**Comment by barrettford** [comment]
The problem was the config version.  I don't know how you managed it, but you were using an old config version.  Normally it would have migrated you, but if you imported an old version it would cause this problem.

**Comment by Sound-Techniker** [comment]
Okay possible that i have stored before the update, to avoid a complett reconfig and reimported i after a Version change. Sounds like my fault.
