### ISSUE TITLE
Plugin suddenly not working anymore, lost all plugin data

### ISSUE THREAD

**Issue by Technofrikus** [barrettford/Octoprint-Usb_keyboard#23]
Hello,

thanks for this great plugin! Build my own little Macropad and its so nice to have some physical buttons for important tasks.

The plugin worked great. I changed the position of my Pi on the printer and forgot to plug in the USB to the printer after that. Next day I plugged in the printer (possibly in another USB port, not sure) while Octopi was running. (Cant remember if the keyboard worked at this point but I think it did). I printed one thing and wanted to print the next thing. Now the keyboard definitely didnt work anymore. I went to the config and it didnt recognize the input from the keyboard anymore, but everything in the plugin screen worked. I tried some other events in the input configuration but didnt help. After a restart to try if that would help, the plugin screen looked like the attached image and no button worked anymore. I tried to access the Ocotoprint page with my iPad (latest iOS) this time, before from my Computer. I doubt that this somehow crashed the plugin, but wanted to mention it.

Reinstalling the plugin without cleaning the data didnt change anything. Unplugging all USB-cables didnt change anything. Reinstalling with cleaning data helped. No it works again but my profile is of course gone. Havent downloaded it before :-/

At least I found your secret text :D 

<img width="729" alt="Screenshot 2021-03-10 at 11 29 44" src="https://user-images.githubusercontent.com/319375/110617978-90d6b600-8196-11eb-9a7c-a303cfdf4b4b.png">

**Comment by barrettford** [comment]
Could you post the usb_keyboard plugin's yaml config from your config.yml file?  Also, if you're able, could you connect to your pi and tell me what you find in /home/pi/.octoprint/data/usb_keyboard directory?  There should be a folder called /profiles and it should have files in it that match the profile strings in the yaml config.

**Comment by Technofrikus** [comment]
Does this make sense if I have reinstalled the plugin with cleaning the data? I guess not.

yaml:
    usb_keyboard:
        _config_version: 2
        profiles:
        -   key: Example QWERTY 60%
            value: 3c5a7631-0363-3ec0-be5f-5170ae4f2741
        -   key: Example 10key - evdev
            value: f4f16627-7c70-3bf0-9e10-19d3f8c1b84e
        -   key: Example 10key - pynput
            value: a96925b2-6271-3a27-b21d-b160da9c9f78
        -   key: Example 10key - pynput with unicode symbols
            value: cc5b31c0-0d47-302f-96e5-a19f59acfae7

in the .backup the content is the same.

**Comment by barrettford** [comment]
K, so the profile entries still exist in your config yaml.  Do the corresponding files exist in the /home/pi/.octoprint/data/usb_keyboard/profiles directory?

**Comment by Technofrikus** [comment]
Yes, they exist, all is back to default. Sadly I can not roll back and reproduce the problematic state. So not reproducable. Next time Ill know where to look :)

**Comment by barrettford** [comment]
You aren't the first person to run into this problem.  I haven't encountered this myself, but my friend also uses the plugin and his profiles also got destroyed somehow.  I haven't been able to figure out why... In the meantime, I'm going to go change my profile cleanup code to be a little less immediate, maybe that will help.

**Comment by barrettford** [comment]
Hopefully I've fixed the bug responsible for this https://github.com/barrettford/Octoprint-Usb_keyboard/releases/tag/v0.2.5

I'm sorry, your lost profile is gone... but I've changed it so that:
1. They shouldn't get deleted like that anymore
2. Even if they're slated for deletion, it'll wait at least 5 days before doing it, so you have time to restore your profile.

**Comment by Technofrikus** [comment]
Thanks, that is great! Will update and remake my profile now :)
