### ISSUE TITLE
GPIO support

### ISSUE THREAD

**Issue by FireMarshmallow** [barrettford/Octoprint-Usb_keyboard#26]
Would it be possible to add GPIO support?
My printer and light are on separate relays, and I control them using the enclosure plug-in.
It would be really sweet if I could have shortcuts for them on my keypad.
Great work by the way, technically not an issue but I didn't know how to get the enhancement icon.

**Comment by barrettford** [comment]
I don't think I will be implementing this at this time.  My plugin already provides a way to send custom Gcode, and several plugins can take custom Gcode to control GPIO.
