### ISSUE TITLE
Settings page doesn't work wih Themeify

### ISSUE THREAD

**Issue by daktylus** [barrettford/Octoprint-Usb_keyboard#28]
The plugin settings page does not work in combination with the Themeify plugin. Many buttons will not be displayed.

**Comment by barrettford** [comment]
[This exact issue is pinned to the top of the issues page.](https://github.com/barrettford/Octoprint-Usb_keyboard/issues)  This is a problem with the Themeify plugin, not mine.  Submit an issue to Themeify to fix their bug.

Again, see https://github.com/barrettford/Octoprint-Usb_keyboard/issues/15 for more information.
