### ISSUE TITLE
device list empty

### ISSUE THREAD

**Issue by ploebb** [barrettford/Octoprint-Usb_keyboard#29]
My device list is empty:

![grafik](https://user-images.githubusercontent.com/5870131/119234943-758e0c80-bb30-11eb-8c57-d44739b58cef.png)

The System is Debian 10 in a virtual machine (vmware esxi) and the USB keyboard is passed through with [virtualhere](https://www.virtualhere.com/) via network.
The keyboard is working fine in terminal.

My /dev/input directory:
```
root@3d:~# ls /dev/input
by-id    event0  event2  event4  event6  event8  mice    mouse1
by-path  event1  event3  event5  event7  event9  mouse0  mouse2
root@3d:~# ls /dev/input/by-id/
usb-046d_0825_E8CB4690-event-if00
usb-04d9_1203-event-if01
usb-04d9_1203-event-kbd
usb-VMware_VMware_Virtual_USB_Mouse-event-mouse
usb-VMware_VMware_Virtual_USB_Mouse-mouse
root@3d:~# ls /dev/input/by-path
pci-0000:02:02.0-usb-0:1:1.0-event-mouse
pci-0000:02:02.0-usb-0:1:1.0-mouse
pci-0000:02:03.0-usb-0:1:1.0-event
platform-i8042-serio-0-event-kbd
platform-i8042-serio-1-event-mouse
platform-i8042-serio-1-mouse
platform-pcspkr-event-spkr
platform-vhci_hcd.0-usb-0:1:1.0-event-kbd
platform-vhci_hcd.0-usb-0:1:1.1-event
```

Am I missing something? How do you get the list of devices?

**Comment by barrettford** [comment]
I have not tested how evdev functions in a Debian 10 VM.  Would you mind performing a few checks for me so we can try and figure things out?  If you'd like to voice chat while we investigate, I have Discord, or we could use Zoom.

**Comment by ploebb** [comment]
Sure! Anything to help! My discord tag is ploebb#8702 .

**Comment by ploebb** [comment]
Well.. this is embarrassing.. To quote: "Have you tried turning it off an on again?" - literally any IT guy 
Apparently I did not try to restart the octoprint service after installing the plugin. The devices appear and work fine after I just did that.

I'm not quite sure what went wrong in the first place because the list even updates fine now if I plug/unplug a device.

**Comment by ploebb** [comment]
I finished the config successfully. Very nice plugin! Thank you!
If I may give some feedback: I had some problems grasping the concept of the variables at first, even with the given examples. A litte explanation on the octoprint plugin repository or somewhere would go a long way for new users I guess.

I really appreciate that you were ready to invest the time to investigate the problem even for such an edge case (VM, Virtual USB,..).
I guess this issue can be closed, but if you still need something, just let me know!

**Comment by barrettford** [comment]
I'm glad you got it working!  Yeah, I haven't best decided how to describe variables... I thought I did an alright job of describing them in the (i) buttons, but you aren't the first person to mention how odd it is...
