### ISSUE TITLE
Trouble installing - Requires Python 3

### ISSUE THREAD

**Issue by jashcroft123** [barrettford/Octoprint-Usb_keyboard#3]
It is not appearing in my plugin manager. When I try and install via url or pip I get:
Command "python setup.py egg_info" failed

**Comment by barrettford** [comment]
Could you provide more context?

1. What are you running Octoprint on? (raspberry pi? windows? mac?)
2. What version of Python are you running?

**Comment by erwann2000** [comment]
> It is not appearing in my plugin manager. When I try and install via url or pip I get:
> Command "python setup.py egg_info" failed

I think you need to update to python3 installation with this link https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by jashcroft123** [comment]
Sorry for the lack of information I'll try and best to explain it now.

1. I'm running Octoprint (pi) on a raspberry pi 3b+
2. I should be running python3 since updating the package I've got a slightly different error message.

`Installing plugin from https://github.com/barrettford/Octoprint-Usb_keyboard/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmp3O0cAR/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmp3O0cAR/master.zip
ERROR: Package 'OctoPrint-Usb-keyboard' requires a different Python: 2.7.16 not in '>=3,<4'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`

This is the output I get when I try and install from the URL through the web console.

When using ssh and installing via pip I get:

`pi@octopi:~ $ ~/oprint/bin/pip2.7 install "https://github.com/barrettford/Octoprint-Usb_keyboard/archive/master.zip"
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/barrettford/Octoprint-Usb_keyboard/archive/master.zip
  Using cached https://github.com/barrettford/Octoprint-Usb_keyboard/archive/master.zip (54 kB)
ERROR: Package 'OctoPrint-Usb-keyboard' requires a different Python: 2.7.16 not in '>=3,<4'
`

**Comment by jashcroft123** [comment]
I have tried using pip instead of pip2.7 as well

**Comment by decay42** [comment]
You probably need to upgrade your octoprint installation to Python 3. I had similar issues. After the upgrade it worked well.

https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by jashcroft123** [comment]
I only had a fresh setup of Octoprint about a month ago so shouldn't that cover me?

**Comment by decay42** [comment]
> I only had a fresh setup of Octoprint about a month ago so shouldn't that cover me?

Apparently not. But if you are on a fresh install of Octopi, there is a simple upgrade script in the blog article linked above that will perform the upgrade for you.

**Comment by jashcroft123** [comment]
I'll give it another shot with a fresh install I had already change the steps in the article.

**Comment by jashcroft123** [comment]
Sorted now. Just the classic fresh install helped. Sorry for wasting everyones time and thanks for the help!
