### ISSUE TITLE
Install Failed...'Requires Different Python'

### ISSUE THREAD

**Issue by FastEddie49** [barrettford/Octoprint-Usb_keyboard#30]
Trying to install on the latest version of Octopi, claims that this requires an earlier version of Python. Image attached.

![image](https://user-images.githubusercontent.com/42302231/119567672-72c62e00-bd61-11eb-8797-b43ca29d70b4.png)

**Comment by barrettford** [comment]
You are misunderstanding the error message.  It says you have python 2.7.16, which isn't at least python version 3 and less than python version 4.
See:
https://github.com/barrettford/Octoprint-Usb_keyboard/issues/5

**Comment by FastEddie49** [comment]
THANK YOU!
    On Tuesday, May 25, 2021, 02:36:51 PM PDT, Barrett Ford ***@***.***> wrote:  
 
 


Closed #30.

**Comment by FastEddie49** [comment]
Hi Barrett!
I bought a cheap wireless keypad, upgraded my Octoprint/Octopi Python, everything works! The USB Keyboard UI was a little bit confusing for me at first, but it begins to make sense with a little trial and error. Yes, I did find your secret text!
Would it be possible to add (or is there already) a "repeat keypress" option? I use Octopi as a frontend to an MPCNC (Mostly Printed CNC) machine that I have built and I want to use the keypad to jog the machine...so right now, I have a gcode command bound to the  Up Arrow key (relative coordinates, G0 Y1 F2100) but to move it 7mm requires 7 keypresses. I would like it to continuously move in 1mm increments for as long as I hold the key down, and stop when I release the key. I don't know if this is possible, but as someone with  barely a smidgen of coding experience I think it would be harder to code against holding a key down than it would be the other way around. My ideal would be a slight delay after the first keypress, then repeating the commands as long as the key is held down.
Regardless, thank you for this awesome plugin, Barrett! There is nothing else like this available that I have found, and typically the keyboard that is connected to the browser controls whatever is connected to the pi...all of us CNC guys want a pendant! I hope to be able to make key assignments that specifies the increment and a key assignment that assigns the direction, but it sure would be sweet if I could continuously jog at whatever increment as long as I held the key down!
--Ed

    On Tuesday, May 25, 2021, 05:33:57 PM PDT, Edward Pinnell ***@***.***> wrote:  
 
  THANK YOU!
    On Tuesday, May 25, 2021, 02:36:51 PM PDT, Barrett Ford ***@***.***> wrote:  
 
 


Closed #30.

**Comment by barrettford** [comment]
It's totally possible to do repeat keys, but I decided against it due to the way that Octoprint buffers printer inputs.  I have no way of controlling exactly how many key presses will register in a set amount of time.  For instance, it is possible that you hold the key down for 5 seconds and get exactly 9 key presses, or you get over 20...  Also, due to octoprint buffering, it will continue to trigger movements after you've released the key.

I recommend, instead, that you either use variables and set useful increments (see some of the examples for how this works) or use several profiles and use a command to switch between them.
