### ISSUE TITLE
Not saving G_codes and BT support

### ISSUE THREAD

**Issue by chromoxdor** [barrettford/Octoprint-Usb_keyboard#4]
Version: 0.1.6

What a wonderful plugin! Thank you!
Since i use a Raspberry Pi 3A+ (only one usb-port and no hub at hand) and having an old bluetooth keyboard lying around i gave it a try.
Plugin recognizes the Keyboard but after turning it off and on again i always have to change to another event and back in the  "Device listener Configuration" to get the inputs recognized again.
Do you think you could take a look at that?

Also the G-Code commands are not being saved. When i go back to the Plugin after saving, they are gone (empty  fields).

Edit: not a big thing, but the plugin doesn’t work well with the themeify-plugin

**Comment by barrettford** [comment]
"Plugin recognizes the Keyboard but after turning it off and on again i always have to change to another event and back in the "Device listener Configuration" to get the inputs recognized again."
Unfortunately, fixing this won't be trivial.  When the keyboard disconnects, it leaves the device in place, and Octoprint is listening on that device.  When it reconnects, it gets a new device and Octoprint has no clue about it.

"Also the G-Code commands are not being saved."
Huge bug!  I'm working on it!

"Edit: not a big thing, but the plugin doesn’t work well with the themeify-plugin"
I'm not sure I'll fix this one.  I also use themeify, but the buttons don't seem to get along...

**Comment by barrettford** [comment]
G-Code fixed in https://github.com/barrettford/Octoprint-Usb_keyboard/commit/08888d3821027711c44ddd19de421cdf92f2bd34

**Comment by chromoxdor** [comment]
> Unfortunately, fixing this won't be trivial. When the keyboard disconnects, it leaves the device in place, and Octoprint is listening on that device. When it reconnects, it gets a new device and Octoprint has no clue about it.

I see...have just tried it with a usb keyboard and replugging it in has the same effect. So a cable makes sense since the device is then always on. 

> I'm not sure I'll fix this one. I also use themeify, but the buttons don't seem to get along...

The workaround is to disable themeify for configuration and enable it afterwards.

**Comment by chromoxdor** [comment]
G-Code Fix seems to work! Thank you!
