### ISSUE TITLE
Install failed - Needs Python 3

### ISSUE THREAD

**Issue by FredGenius** [barrettford/Octoprint-Usb_keyboard#5]
Installing plugin from https://github.com/barrettford/Octoprint-Usb_keyboard/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpQHaYJD/master.zip --no-cache-dir
Processing /tmp/tmpQHaYJD/master.zip
OctoPrint-Usb-keyboard requires Python '>=3,<4' but the running Python is 2.7.13
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

I see now, requires Python V3 - maybe state clearly on homepage?

**Comment by barrettford** [comment]
This plugin requires python 3 instead of the default python 2 your installation comes with.  See https://octoprint.org/blog/2020/09/10/upgrade-to-py3/ for how to upgrade.

**Comment by FredGenius** [comment]
Thanks, looking forward to using this plugin.

 

Fred Ö¿Ö
