### ISSUE TITLE
Not in the Octoprint plugin manager

### ISSUE THREAD

**Issue by DemonHunter759** [barrettford/Octoprint-Usb_keyboard#6]
So either my octoprint is complety broken or whatever....

I can't find the plugin in the plugin manager.

Dunno if i search wrong or its some other weirdness

Because i really like your plugin for controlling my printer when im at the physical location where it's located.
Below is the link i copied into the octoprint plugin manager:

Installiere Plugin von https://github.com/barrettford/OctoPrint-Usb_keyboard/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmp_EUOuS/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmp_EUOuS/master.zip
ERROR: Package 'OctoPrint-Usb-keyboard' requires a different Python: 2.7.16 not in '>=3,<4'
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jashcroft123** [comment]
I had the same issue you need to update your python, have a read of the thread here:
https://github.com/barrettford/Octoprint-Usb_keyboard/issues/3

**Comment by DemonHunter759** [comment]
thy 

curl -L https://get.octoprint.org/py3/upgrade.py --output upgrade.py
python3 upgrade.py

did it for me
