### ISSUE TITLE
any documention?

### ISSUE THREAD

**Issue by bertoo87** [barrettford/Octoprint-Usb_keyboard#7]
Hi there :)
i installed the plugin, but after 2 hours of tryhard mode i cant get it to do anything.
is there any documentation on how to set up simple commands? i connected a standard full sized keyboard to the pi. would love to see this working, cause my printer is in another room, that plugin would save me a lot of time.

**Comment by jashcroft123** [comment]
It's likely that you haven't selected the correct USB input for the keyboard. On the settings at the top, there is device listener config. If you go into that you should be able to work it out

**Comment by bertoo87** [comment]
> It's likely that you haven't selected the correct USB input for the keyboard. On the settings at the top, there is device listener config. If you go into that you should be able to work it out

damn you are right. i got it working now. i feel a little bit embarrassed. thanks for that lightning fast reply :)

**Comment by jashcroft123** [comment]
No worries took me a while to figure it out as well
