### ISSUE TITLE
Superb!

### ISSUE THREAD

**Issue by FredGenius** [barrettford/Octoprint-Usb_keyboard#8]
This is superb, many thanks!

Suggestions:- 
Would be nice to be able edit the gcode (greyed-out), or copy/paste into another field...
Export a profile, so can be imported on another Octoprint instance...
Handling of NUMLOCK button, so one key can have two functions?

**Comment by barrettford** [comment]
Addressed in https://github.com/barrettford/Octoprint-Usb_keyboard/commit/7c02e7aa4d865e59f1ff9d1edf957e81ac861872

Not going to add modifier keys at this time, please see https://github.com/barrettford/Octoprint-Usb_keyboard/issues/2
