### ISSUE TITLE
OctoPi shutdown option

### ISSUE THREAD

**Issue by Marro64** [barrettford/Octoprint-Usb_keyboard#9]
Hi!
I would love the ability to shutdown the Pi via the keyboard, would save me from having to having to walk to my computer before turning the power off. I do think it would need options to protect against both accidental presses like with the OctoPrint commands and shutting down while the extruder is still hot (printing) like with the PSU control commands.

**Comment by Technofrikus** [comment]
Agreed, that would be great!

**Comment by barrettford** [comment]
I am working on this right now.  I new release with this feature set should be out in the next day or two.  If you'd be interested in testing it, you can manually install https://github.com/barrettford/OctoPrint-Usb_keyboard/archive/investigate-restart.zip

Be warned, this isn't yet fully tested and there may be bugs.  Please back-up your configuration before you try installing this test version.

**Comment by barrettford** [comment]
So... Does it work?  If so, I can release this out for everyone.

**Comment by Marro64** [comment]
Been busy so haven't had much time to use it, but the shutdown_system after 5 presses seems to work fine and my config didn't get corrupted.

**Comment by Technofrikus** [comment]
Agreed, shutdown works :) Thanks!
